services:
  app:
    container_name: todo-app
    image: node:20
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - internal
      - marco

  db:
    container_name: todo-db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./docker/data/mongo:/data/db

  rabbitmq:
    container_name: todo-rabbitmq
    image: rabbitmq:4-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - internal
      - marco

  mongo-express:
    container_name: todo-mongo-express
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - internal
      - marco

networks:
  marco:
    name: marco
    external: true
  internal:
    driver: bridge

volumes:
  rabbitmq-lib:
  rabbitmq-log:
